#!/usr/bin/ruby

#
# scripts/area
# Area testing and test-playing script for Solace
# By Ryan Sandor Richards
#

require "rexml/document"

AREA_DIR = "data/areas/"

def usage
  puts "Usage: area [test | play] <area name>"
  puts "\ttest - Parses and tests area for common errors and prints a report."
  puts "\tplay - Allows you to walk through areas offline"
end

# Test area run mode
def test area
  filename = AREA_DIR + area + ".xml"
  puts "Loading " + filename + "..."
end

# Play area run mode
def play area
  filename = AREA_DIR + area + ".xml"
  puts "Loading " + filename + "..."
end

# Basic commands
modes = ["test", "play"]

# Determine what to do
if ARGV.length != 2 or not modes.include? ARGV[0]
  usage 
elsif ARGV[0] == "test"
  test ARGV[1]
elsif ARGV[0] == "play"
  play ARGV[1]
end

